config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'main/contact'
  get 'main/about'
  get 'main/blog'
  get 'main/reStockInventory'
  get 'main/buy'

  root 'main#index'

end

app/models/drink_mem.rb
#
# Title: DrinkMem
# Description: 
#
# Author: rholl00 
# Date: 12/31/14
#

class DrinkMem
  attr_accessor :number, :name, :displayName, :recipe, :cost, :inStock

  def initialize(number, name, displayName, recipe)
    @number = number
    @name = name
    @displayName = displayName
    @recipe = recipe
  end

  def to_s
    "number: #{@number} name: #{@name} "
  end


end

app/models/inventory_entry_mem.rb
#
# Title: InventoryEntryMem
# Description: 
#
# Author: rholl00 
# Date: 12/31/14
#

class InventoryEntryMem
  attr_accessor :displayName, :name, :cost, :count

  def initialize(displayName,name,cost,count)
    @displayName = displayName
    @name = name
    @cost = cost
    @count = count
  end

  def consumeIngredient(decrCount)
    @count > decrCount ? @count -= decrCount : @count =0

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
#
# Title: MainController
# Description: Main Baristamatic controller
#
# Author: rholl00
# Date: 12/10/14
#

class MainController < ApplicationController

  def index
    puts "index: called with params - #{params}"
    @inventory = BaristaServiceMem.instance.getInventoryAvailable
    @drinks = BaristaServiceMem.instance.getDrinks
  end

  def about
  end

  def blog
  end

  def contact

  end

  def reStockInventory
    puts "reStockInventory: called"
    BaristaServiceMem.instance.reStockInventory
    redirect_to action: 'index', status: 303
  end

  def buy
    puts "buy: called for drink #{params['number']}"
    BaristaServiceMem.instance.orderDrink(params['number'])
    redirect_to action: 'index', status: 303
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<%# Title: application.html.erb %>
<%# Main layout page - turbolinks are turned off %>
<%# Author: RH %>

<!DOCTYPE html>
<html>
<head>
    <title>TestBaristamaticRailsBootstrap</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min" %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag "baristamatic" %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <%= javascript_include_tag 'jquery-1.11.2.min.js' %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag 'bootstrap.min.js' %>
</head>
<body>
<div class="brand">Baristamatic</div>
<div class="address-bar">302 Wilcox Street | Castle Rock, CO 80104 | 123.456.7890</div>

<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="<%= url_for main_index_path %>">Baristamatic</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="<%= url_for main_index_path %>">Home</a>
                </li>
                <li>
                    <a href="<%= url_for main_about_path %>">About</a>
                </li>
                <li>
                    <a href="<%= url_for main_blog_path %>">Blog</a>
                </li>
                <li>
                    <a href="<%= url_for main_contact_path %>">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<%= yield %>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <p>WebPilot LLC 2014</p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

app/views/main/_place_order.html.erb
<%# Title: _place_order.html.erb %>
<%# Order partial page %>
<%# Author: RH %>

<a name="buyAnchor"></a>
<div class="row">
    <div class="box">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <hr>
            <h2 class="intro-text text-center">Place your
                <strong>order</strong>
            </h2>
            <hr>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th data-field="id">Item</th>
                    <th data-field="name">Quantity</th>
                    <th data-field="name">Cost</th>
                    <th data-field="name" data-halign="center" data-align="center">Currently Available</th>
                    <th data-field="name">Buy</th>
                </tr>
                </thead>
                <%# The drinks attribute is passed in from index.html.erb using the render method %>
                <% drinks.each do |drink| %>
                   <tr>
                       <td><%= drink.number %></td>
                       <td><%= drink.displayName %></td>
                       <td><%= number_to_currency(drink.cost) %></td>
                       <td data-halign="center" data-align="center"><%= drink.inStock ? 'Yes' : 'No' %></td>
                       <%# Adding the anchor: parameter will add a # (jump to) in the redirect url that causes the page to jump to this buy section of the page %>
                       <td><%= link_to 'Buy', main_buy_path(number: drink.number, anchor: 'buyAnchor'), :class => 'buy-btn btn btn-large btn-primary', :disabled => !drink.inStock %></td>
                   </tr>
                <% end %>
            </table>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/main/_view_inventory.html.erb
<%# Title: _view_inventory.html.erb %>
<%# Inventory view partial page %>
<%# Author: RH %>

<a name="invAnchor"></a>
<div class="row">
    <div class="box">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <hr>
            <h2 class="intro-text text-center">Our current
                <strong>inventory</strong>
            </h2>
            <hr>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th data-field="id">Item</th>
                    <th data-field="name">Quantity</th>
                </tr>
                </thead>
                <%# The inventory attribute is passed in from index.html.erb using the render method %>
                <% inventory.each do |inv| %>
                   <tr>
                       <td><%= inv.displayName %></td>
                       <td><%= inv.count %></td>
                   </tr>
                <% end %>
            </table>
            <div class="text-center">
                <%# Use main_reStockInventory_path path helper to link to /main/reStockInventory %>
                <%= link_to 'Restock Inventory', main_reStockInventory_path(anchor: 'invAnchor'), :class => 'btn btn-large btn-primary' %>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/main/about.html.erb
<%# Title: about.html.erb %>
<%# About page %>
<%# Author: RH %>

<div class="container">
   <div class="row">
      <div class="box">
         <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">About
               <strong>Baristamatic</strong>
            </h2>
            <hr>
         </div>
         <div class="col-md-6">
            <img class="img-responsive img-border-left" src="<%= image_path('slide-1.jpg') %>" alt="">
         </div>
         <div class="col-md-6">
            <p>Great drinks at the Rock.</p>

            <p>Open sunrise to sunset</p>
         </div>
         <div class="clearfix"></div>
      </div>
   </div>
</div>

app/views/main/blog.html.erb
<%# Title: blog.html.erb %>
<%# Blog page %>
<%# Author: RH %>

<div class="container">
   <div class="row">
      <div class="box">
         <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Baristamatic
               <strong>blog</strong>
            </h2>
            <hr>
         </div>
         <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="<%= image_path('slide-2.jpg') %>" alt="">

            <h2>Not bad
               <br>
               <small>October 13, 2013</small>
            </h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats
               vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit
               voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
               veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
         </div>
         <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="<%= image_path('slide-1.jpg') %>" alt="">

            <h2>Best I ever had
               <br>
               <small>October 13, 2013</small>
            </h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats
               vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit
               voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
               veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
         </div>
         <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="<%= image_path('slide-3.jpg') %>" alt="">

            <h2>Fairly good
               <br>
               <small>October 13, 2013</small>
            </h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats
               vitaes nemo minima rerums unsers sadips amets. </p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
         </div>
         <div class="col-lg-12 text-center">
            <ul class="pager">
               <li class="previous"><a href="#">&larr; Older</a>
               </li>
               <li class="next"><a href="#">Newer &rarr;</a>
               </li>
            </ul>
         </div>
      </div>
   </div>
</div>
<!-- /.container -->

app/views/main/contact.html.erb
<%# Title: contact.html.erb %>
<%# Contact page %>
<%# Author: RH %>

<div class="container">
   <div class="row">
      <div class="box">
         <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Contact
               <strong>Baristamatic</strong>
            </h2>
            <hr>
         </div>
         <div class="col-md-8">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                    src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=39.372520,-104.859675&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
         </div>
         <div class="col-md-4">
            <p>Phone:
               <strong>123.456.7890</strong>
            </p>

            <p>Email:
               <strong><a href="mailto:baristamatic@gmail.com">baristamatic@gmail.com</a></strong>
            </p>

            <p>Address:
               <strong>302 Wilcox Street
                  <br>Castle Rock, CO 80104</strong>
            </p>
         </div>
         <div class="clearfix"></div>
      </div>
   </div>
   <div class="row">
      <div class="box">
         <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Contact
               <strong>form</strong>
            </h2>
            <hr>


            <form role="form">
               <div class="row">
                  <div class="form-group col-lg-4">
                     <label>Name</label>
                     <input type="text" class="form-control">
                  </div>
                  <div class="form-group col-lg-4">
                     <label>Email Address</label>
                     <input type="email" class="form-control">
                  </div>
                  <div class="form-group col-lg-4">
                     <label>Phone Number</label>
                     <input type="tel" class="form-control">
                  </div>
                  <div class="clearfix"></div>
                  <div class="form-group col-lg-12">
                     <label>Message</label>
                     <textarea class="form-control" rows="6"></textarea>
                  </div>
                  <div class="form-group col-lg-12">
                     <input type="hidden" name="save" value="contact">
                     <button type="submit" class="btn btn-default">Submit</button>
                  </div>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- /.container -->

app/views/main/index.html.erb
<%# Title: index.html.erb %>
<%# Main page %>
<%# Author: RH %>



<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12 text-center">
                <div id="carousel-example-generic" class="carousel slide">
                    <!-- Indicators -->
                    <ol class="carousel-indicators hidden-xs">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img class="img-responsive img-full" src="<%= image_path('slide-1.jpg') %>" alt="">
                        </div>
                        <div class="item">
                            <img class="img-responsive img-full" src="<%= image_path('slide-2.jpg') %>" alt="">
                        </div>
                        <div class="item">
                            <img class="img-responsive img-full" src="<%= image_path('slide-3.jpg') %>" alt="">
                        </div>
                    </div>
                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="icon-prev"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="icon-next"></span>
                    </a>
                </div>
                <h2 class="brand-before">
                    <small>Welcome to</small>
                </h2>
                <h1 class="brand-name">Baristamatic</h1>
                <hr class="tagline-divider">
                <h2>
                    <small>By
                        <strong>WebPilot LLC</strong>
                    </small>
                </h2>
            </div>
        </div>
    </div>
    <!-- Place order partial-->
    <%= render(partial: 'place_order', :locals => {drinks: @drinks}) %>

    <!-- Inventory partial-->
    <%= render(partial: 'view_inventory', :locals => {inventory: @inventory}) %>
</div>
<!-- /.container -->





<!-- Script to Activate the Carousel -->
<script>
   $('.carousel').carousel({
      interval: 5000 //changes the speed
   })
</script>